### ISSUE TITLE
I like this program so much, some questions

### ISSUE THREAD

**Issue by xiamuguizhi** [petabyt/tinyblog#1]
I am running locally http://localhost/ and the following error is prompted : 

`Notice: Undefined index: post in C:\phpEnv\www\localhost\index.php on line 36`

```php

$specificPost = $_GET["post"];   //   Undefined ?


@$specificPost = $_GET["post"];   // I added @ so that it does not output error problems

``` 

Why is the file in .md format, so I want to format and write?

```php

$text = file_get_contents("posts/" . strval($post) . ".md"); //改为markdown格式

```
I'm still testing it locally, and it's like a beauty that fascinates me firmly.

**Comment by petabyt** [comment]
Thanks for helping test it :)  
As for `$specificPost = $_GET["post"];`, I was never aware that it caused a warning, I'll add your fix to the code.  
As for your second question, I'm not sure what you are asking, are you confused on how it reads the files?

Here's my post folder for reference: https://petabyt.dev/blog/posts/

**Comment by xiamuguizhi** [comment]
Sorry for the problem with my description. I think that since I use markdwon to write, I use 1/2/3 by default without any suffix. Some editors cannot effectively consider it as a file. If you use 1.md/2.md/3.md like this Is the markdown file more friendly?

Of course this is my personal understanding.

I am using Google Translate Chinese to English. I don’t know if you can understand this passage.

I currently solve the first problem like this

```php
		# Show specific post or all
		if (!isset($_GET["post"])) {
			for ($post = $postCount; $post >= 1; $post--) {
				makePost($post, FALSE);
			}
		} else {
			makePost($_GET["post"], TRUE);
		}
```

**Comment by petabyt** [comment]
I don't have Markdown syntax highlighting in my text editor, so I never bothered with it.

Maybe try www.deepl.com, I heard it is more accurate.

**Comment by xiamuguizhi** [comment]
@petabyt  So that's it, I use vscode editor to write markdown articles.

I'm now trying to add a theme to it.

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/c725e1b0-019d-46a5-b04d-34b5c2208edc.png)

**Comment by xiamuguizhi** [comment]
@petabyt I submitted a topic that you can review

## home

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/6316d710-2bb6-4224-8ca2-7b14807f5896.png)

## post

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/f2734165-b95e-490c-a3ae-602e71568708.png)

**Comment by xiamuguizhi** [comment]
I added a pagination feature, but the writing style needs to be changed

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/40b6e376-0fd1-40a4-84cc-6b40749e7b45.png)

The original way:

```
# CrypticOS: My Quarantine Project.
Feb 4 2021

A BrainFck operating system...

I wanted to make an x86 operating system.
Except that the programs would be written in BrainFck. I knew I could learn a lot
from it, especially since I don鈥檛 know x86 assembler very well.

Yes, BrainFck with a u. Wasn't comfortable with putting it everywhere.
```

Now: 

```
CrypticOS: My Quarantine Project@29@Feb 4 2021@A BrainFck operating system...I wanted to make an x86 operating system.

# CrypticOS: My Quarantine Project.
Feb 4 2021

A BrainFck operating system...

I wanted to make an x86 operating system.
Except that the programs would be written in BrainFck. I knew I could learn a lot
from it, especially since I don鈥檛 know x86 assembler very well.

Yes, BrainFck with a u. Wasn't comfortable with putting it everywhere.
```

I'm splitting the` @ ` symbol to get the corresponding ` title @id @time @article description` 。

Manually adding the corresponding markdown parsing format was too difficult for me, I used the 
`https://github.com/SegmentFault/HyperDown` parser which is only 48kb and lightweight

I don't know if you or others need it, and I need the features, but to make him clean and light, and for not being able to code php I need a lot of google searches.

I'm considering rss at a later stage? Maybe I should add a simple admin to manage it only need to post articles to create `1/2/3/4/5` so that posts are good, hope I can succeed may God bless me

**Comment by xiamuguizhi** [comment]
@petabyt 

http://121.5.226.246/

This is the 5630 article test site, you can view it

By the way it has pagination

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/b85fc9e0-4686-41e6-8d53-3d56fbb0ec92.png)

It's late at night in China, I need to sleep, good night

**Comment by petabyt** [comment]
Adding new libraries would go directly against my original philosophy for the  
project - Be as *simple* and as *small* as possible.  
I'm fine with adding alternative version, but at that point it wouldn't be so "tiny" anymore...

> I'm considering rss at a later stage?

Considering my current format, I could see myself making a Python script to generate one.

**Comment by xiamuguizhi** [comment]
@petabyt I understand your original intention, minus `Parser.php` I only have a total of 9kb size, I manually added some markdown parsing that I wanted to correspond to and it didn't seem to work, so I struggled for a long time before adding `Parser.php`. 

I tried to generate ` rss.php` file with php for , I'll try to see today.

**Comment by petabyt** [comment]
Are you using a Regex playground like https://regex101.com/ for testing? It's a pain to do Regex without something like that.

**Comment by xiamuguizhi** [comment]
![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/42cc0d99-0559-4ce3-99b6-d6469d0a4e1d.png)

I've got it working, I'm following the paginated output rss.xml with pagination to control the number of outputs.

The core is still the same as I mentioned to you yesterday, splitting `@` into arrays and taking values out of the arrays.

**Comment by xiamuguizhi** [comment]
I want this program to restore as much functionality as possible as I did with `https://xiamuyourenzhang.cn/`.

Currently my next requirement is how to request a standalone page, I tried to create a new `about` file but it doesn't output properly and is stored in an array by `postsDirectory`.

I'm thinking of creating a new folder `/post/page/about` under the `post` folder, can this not be stored? Or is there another way I can request an `about` page about me?

Translated with www.DeepL.com/Translator (free version)

**Comment by xiamuguizhi** [comment]
![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/075e7bb3-ad48-4771-be16-9bbf3255ec85.png)

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/1c9f7173-e1af-476b-9902-29718ebb5ca3.png)

```php
for ($post = $postCount -"3"; $post >= 1; $post--) {
```

Less 3 three separate pages

**Comment by petabyt** [comment]
Why not just make a separate about.php page?

**Comment by xiamuguizhi** [comment]
@petabyt The first is because I don't know php code, and the second is that I just need a page that shows about me.

The third is as small as possible like you said.

**Comment by xiamuguizhi** [comment]
@petabyt  I have successfully migrated to `tinyblog ` can you recognize it, I used the new theme.

It also has a simple article publishing as generating *.MD files

I use a popular third-party commenting system in China

blog url：https://xiamuyourenzhang.cn/

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/44a736ac-a3c5-4541-915b-c44705b2b06a.png)


It is as small as ever, except for a markdown parser 48kb
