### ISSUE TITLE
?post= Vulnerability

### ISSUE THREAD

**Issue by petabyt** [petabyt/tinyblog#5]
the `post` parameter is never checked to be a valid number. This means I can use tinyblog to get the contents of any file on the system that the web server has access to.

Fix:  
```
if (isset($_GET["post"])) {
	if (!is_numeric($_GET["post"])) {
		echo("Invalid post");
		die();
	}
}
```

**Comment by xiamuguizhi** [comment]
You can try it on me. I don't feel it's a big problem.  https://xiamuyourenzhang.cn/   

Can we restrict it in nginx or something?

**Comment by petabyt** [comment]
> You can try it on me. I don't feel it's a big problem. https://xiamuyourenzhang.cn/
> 
> Can we restrict it in nginx or something?

It is a big problem. Worst case scenario, somebody could use it to get SSH keys or other confidential information.  
For some reason it doesn't seem to be working on your end: https://xiamuyourenzhang.cn/?post=../index.php

**Comment by xiamuguizhi** [comment]
@petabyt I misunderstood, I thought you were just reading my article file `post\1`.

If it's what you're listing now I feel like there's a real problem and I don't know why it didn't work? Am I using pseudo-static or? I also opened a firewall on the server to protect against some regular attacks, I don't know if it blocked

**Comment by petabyt** [comment]
https://xiamuyourenzhang.cn/?post=../../../index.php returns a different request.

**Comment by xiamuguizhi** [comment]
@petabyt I have added your code, now I should be able to rest assured.
